version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: kyeto_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: kyeto_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: kyeto_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/chat_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./frontend
    container_name: kyeto_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
